networks:
  test_net:
    driver: bridge

services:
  mvta-test:
    build: .
    ports:
      - "${MVTA_PORT}:${MVTA_PORT}"
    depends_on:
      mvta-redis-test:
        condition: service_healthy
    links:
      - mvta-redis-test
    networks:
      - test_net
    environment:
      - REDIS_HOST=mvta-redis-test
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PWD=${REDIS_PWD}
      - MVTA_RATELIMITMINUTES=${MVTA_RATELIMITMINUTES}
      - MVTA_RATELIMITREQUESTS=${MVTA_RATELIMITREQUESTS}
      - MVTA_PORT=${MVTA_PORT}
      - MVTA_HOST=${MVTA_HOST}
      - MVTA_PROTOCOL=${MVTA_PROTOCOL}
      - NODE_ENV=test
    user: "node"
    healthcheck:
      test: ["CMD", "curl", "-f", "${MVTA_PROTOCOL}://${MVTA_HOST}:${MVTA_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/usr/src/mvta
    restart: unless-stopped

  mvta-redis-test:
    build:
      context: .
      dockerfile: Dockerfile.redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10
    environment:
      - REDIS_HOST=mvta-redis-test
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PWD=${REDIS_PWD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - test_net
    restart: unless-stopped

volumes:
  redis-data: