networks:
  backend_net:
    driver: bridge

services:
  mvta:
    build: .
    ports:
      - "${MVTA_PORT}:${MVTA_PORT}"
    depends_on:
      mvta-redis:
        condition: service_healthy
    links:
      - mvta-redis
    networks:
      - backend_net
    environment:
      - REDIS_HOST=mvta-redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PWD=${REDIS_PWD}
      - MVTA_RATELIMITMINUTES=${MVTA_RATELIMITMINUTES}
      - MVTA_RATELIMITREQUESTS=${MVTA_RATELIMITREQUESTS}
      - MVTA_PORT=${MVTA_PORT}
      - MVTA_HOST=${MVTA_HOST}
      - NODE_ENV=production
    volumes:
      - .:/usr/src/mvta
    restart: unless-stopped

  mvta-redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10
    environment:
      - REDIS_HOST=mvta-redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PWD=${REDIS_PWD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend_net
    restart: unless-stopped

volumes:
  redis-data: