services:
  mvta:
    build: .
    ports:
      - "${MVTA_PORT}:${MVTA_PORT}"
    depends_on:
      mvta-redis:
        condition: service_healthy
    links:
      - mvta-redis
    environment:
      - REDIS_HOST=mvta-redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PWD=${REDIS_PWD}
      - MVTA_RATELIMITMINUTES=0.5
      - MVTA_RATELIMITREQUESTS=50
      - MVTA_PORT=${MVTA_PORT}
      - MVTA_HOST=${MVTA_HOST}
      - NODE_ENV=production
    volumes:
      - .:/usr/src/mvta
    restart: unless-stopped

  mvta-redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    restart: unless-stopped

volumes:
  redis-data: